using DotNetAPI.Models;
using Microsoft.EntityFrameworkCore;

namespace DotNetAPI.Data;

public class DataContextEF(IConfiguration config) : DbContext
{
    private readonly IConfiguration _config = config;

    // these map our models to our database tables
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserJobInfo> UserJobInfo { get; set; }
    public virtual DbSet<UserSalary> UserSalary { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("TutorialAppSchema");

        // this is to tell EF that it should look for the
        // UserS table when mapping User 
        modelBuilder.Entity<User>()
                    .ToTable("Users", "TutorialAppSchema")
                    .HasKey(u => u.UserId); // tells EF that this is an autogenerated key

        modelBuilder.Entity<UserJobInfo>()
                    .HasKey(u => u.UserId);

        modelBuilder.Entity<UserSalary>()
                    .HasKey(u => u.UserId);
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if(!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(_config.GetConnectionString("DefaultConnection"), 
                                        options => options.EnableRetryOnFailure());
        }
    }
}